package com.cms.orderservices.controllers;

import com.cms.orderservices.entities.Order;
import com.cms.orderservices.repositories.OrderRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/order") // This means URL's start with /order (after Application path)
public class OrderController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private OrderRepository orderRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestParam Integer productId,
                                            @RequestParam String productName,
                                            @RequestParam Double productPrice) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Order o = new Order();

        o.setProductId(productId);
        o.setProductName(productName);
        o.setProductPrice(productPrice);
        orderRepository.save(o);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Order> getAllUsers() {
        // This returns a JSON or XML with the users
        return orderRepository.findAll();
    }
}
